spring:
  cloud:
    function:
      definition: paymentEventConsumer;ordersProducer;ordersProcessor
    stream:
      bindings:
        paymentEventConsumer-in-0:
          destination: payments
          content-type: application/json
#          consumer:
#              use-native-decoding: false
        ordersProducer-out-0:
          destination: orders
          content-type: application/json
#          producer:
#            use-native-encoding: false
        ordersProcessor-out-0:
          destination: payments
          content-type: application/json
        ordersProcessor-in-0:
          destination: orders
          content-type: application/json


      kafka:
        binder:
          brokers: localhost:9092

      #        bindings:
#          ordersProducer-out-0:
#            producer:
#              configuration:
#                value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
#                key.serializer: org.apache.kafka.common.serialization.StringSerializer
#          ordersConsumer-in-0:
#            consumer:
#              configuration:
#                value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
#                key.serializer: org.apache.kafka.common.serialization.StringSerializer
      default-binder: kafka

server:
  port: 8097
